# frozen_string_literal: true

def square_mock_data
  [{ type: 'ITEM',
     id: 'DSXZZ6NUR67KKKXHCH7UOPCG',
     updated_at: '2023-07-25T18:19:54.996Z',
     created_at: '2023-07-25T18:19:54.996Z',
     version: 1_690_309_194_996,
     is_deleted: false,
     present_at_all_locations: true,
     item_data: { name: 'Fake Item',
                  description: 'This is a fake item for testing purposes',
                  is_taxable: true,
                  visibility: 'PRIVATE',
                  variations: [{ type: 'ITEM_VARIATION',
                                 id: 'QPKIHYCMFW7IYL32GDNUZJ3Y',
                                 updated_at: '2023-07-25T18:19:54.996Z',
                                 created_at: '2023-07-25T18:19:54.996Z',
                                 version: 1_690_309_194_996,
                                 is_deleted: false,
                                 present_at_all_locations: true,
                                 item_variation_data: { item_id: 'DSXZZ6NUR67KKKXHCH7UOPCG',
                                                        name: '',
                                                        ordinal: 0,
                                                        pricing_type: 'FIXED_PRICING',
                                                        price_money: { amount: 100, currency: 'USD' },
                                                        available_for_booking: true,
                                                        sellable: true,
                                                        stockable: true } }],
                  product_type: 'REGULAR',
                  description_html: '<p>This is a fake item for testing purposes</p>',
                  description_plaintext: 'This is a fake item for testing purposes' } },
   { type: 'ITEM',
     id: 'WROKPXTQF7CCXZHKFTNSOWS5',
     updated_at: '2023-07-25T18:20:22.327Z',
     created_at: '2023-07-25T18:20:22.327Z',
     version: 1_690_309_222_327,
     is_deleted: false,
     present_at_all_locations: true,
     item_data: { name: 'Fake Item',
                  description: 'This is a fake item for testing purposes',
                  is_taxable: true,
                  visibility: 'PRIVATE',
                  variations: [{ type: 'ITEM_VARIATION',
                                 id: '36WUEVZO7TZMYZ6BKH4E6FQG',
                                 updated_at: '2023-07-25T18:20:22.327Z',
                                 created_at: '2023-07-25T18:20:22.327Z',
                                 version: 1_690_309_222_327,
                                 is_deleted: false,
                                 present_at_all_locations: true,
                                 item_variation_data: { item_id: 'WROKPXTQF7CCXZHKFTNSOWS5',
                                                        name: '',
                                                        ordinal: 0,
                                                        pricing_type: 'FIXED_PRICING',
                                                        price_money: { amount: 100, currency: 'USD' },
                                                        available_for_booking: true,
                                                        sellable: true,
                                                        stockable: true } }],
                  product_type: 'REGULAR',
                  description_html: '<p>This is a fake item for testing purposes</p>',
                  description_plaintext: 'This is a fake item for testing purposes' } }]
end
